version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  sites:
    build: ./sites
    ports:
      - "8080:8080"
    volumes:
      - ./sites:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development